version: 0.0
resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: my-lambda-function-name
        Alias: live
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
